version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8080"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  auth_data:
